export const styles = {
  navbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#282c34',
    padding: '20px 0px',
    color: '#ffffff',
    fontFamily: "'Poppins', sans-serif",
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    top: 0,
    left: 0,
    width: '100%',
    position: 'absolute' as const,
  },
  divLogo: {
    display: 'flex',
  },
  logo: {
    width: '150px',
  },
  links: {
    display: 'flex',
    gap: '20px',
    padding: '0 50px',
  },
  mainContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100vw',
    height: '100vh',
    backgroundColor: '#1e1e2f',
    fontFamily: "'Poppins', sans-serif",
  },
  appContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    backgroundColor: 'rgba(36, 36, 36, 0.9)',
    padding: '30px',
    borderRadius: '15px',
    color: '#f5f5f5',
    fontFamily: "'Poppins', sans-serif",
    border: '1px solid rgba(255, 255, 255, 0.2)',
    maxWidth: '1000px',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.37)',
    backdropFilter: 'blur(10px)',
  },
  exercicioContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    backgroundColor: 'rgba(85, 85, 85, 0.8)',
    padding: '20px',
    borderRadius: '15px',
    color: '#ffffff',
    marginBottom: '20px',
    fontFamily: "'Poppins', sans-serif",
    width: '570px',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.25)',
    backdropFilter: 'blur(8px)',
    maxHeight: '70vh',
    overflowY: 'auto' as const,
  },
  displayContainer: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '10px',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    borderRadius: '10px',
    minHeight: '60px',
    width: '100%',
  },
  titulo: (color: string) => ({
    fontSize: '28px',
    color,
    alignSelf: 'flex-start',
    fontWeight: '600',
    textShadow: '0 2px 4px rgba(0, 0, 0, 0.5)',
  }),
  numero: {
    backgroundColor: '#209869',
    color: '#ffffff',
    padding: '2px',
    borderRadius: '50%',
    width: '50px',
    height: '50px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    fontWeight: 'bold',
    margin: '5px',
    cursor: 'pointer',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.3)',
    transition: 'transform 0.2s, box-shadow 0.2s',
    ':hover': {
      transform: 'scale(1.1)',
      boxShadow: '0 6px 15px rgba(0, 0, 0, 0.5)',
    },
  },
  welcomeBtn: {
    backgroundColor: '#4CAF50',
    color: '#ffffff',
    padding: '10px 20px',
    borderRadius: '8px',
    border: 'none',
    fontSize: '16px',
    cursor: 'pointer',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.3)',
    transition: 'background-color 0.3s, transform 0.2s',
    ':hover': {
      backgroundColor: '#45a049',
      transform: 'scale(1.05)',
    },
  },
  clearBtn: {
    backgroundColor: '#800020',
    color: '#fff',
    padding: '10px 20px',
    borderRadius: '8px',
    border: 'none',
    fontSize: '16px',
    cursor: 'pointer',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.3)',
    transition: 'background-color 0.3s, transform 0.2s',
    ':hover': {
      backgroundColor: '#CC0000',
      transform: 'scale(1.05)',
    },
  },
  attemptContainer: {
    display: 'flex',
    gap: '10px',
    padding: '10px',
    marginBottom: '5px',
    border: '1px solid #209869',
    borderRadius: '12px',
  },
  suggestion: { display: 'flex', gap: '10px', paddingBottom: '50px' },
};
