export const styles = {
  themeToggle: {
    position: 'fixed' as const,
    bottom: '20px',
    left: '20px',
    backgroundColor: '#4CAF50',
    color: '#fff',
    border: 'none',
    borderRadius: '50%',
    width: '50px',
    height: '50px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.3)',
  },
  darkTheme: {
    backgroundColor: '#1e1e2f',
    color: '#fff',
    minHeight: '100vh',
  },
  lightTheme: {
    backgroundColor: '#f9f9f9',
    color: '#000',
    minHeight: '100vh',
  },

  // Geral
  mainContainer: {
    boxSizing: 'border-box' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100vw',
    height: '100vh',
    fontFamily: "'Poppins', sans-serif",
    maxHeight: '100vh' as const,
    overflowY: 'auto' as const,
    paddingTop: '50px',
  },
  appContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    backgroundColor: 'rgba(36, 36, 36, 0.9)',
    padding: '30px',
    borderRadius: '15px',
    color: '#f5f5f5',
    fontFamily: "'Poppins', sans-serif",
    border: '1px solid rgba(255, 255, 255, 0.2)',
    maxWidth: '1000px',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.37)',
    backdropFilter: 'blur(10px)',
  },
  exercicioContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    backgroundColor: 'rgba(85, 85, 85, 0.8)',
    padding: '20px',
    borderRadius: '15px',
    color: '#ffffff',
    marginBottom: '20px',
    fontFamily: "'Poppins', sans-serif",
    width: '700px',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.25)',
    backdropFilter: 'blur(8px)',
    maxHeight: '70vh',
    overflowY: 'auto' as const,
  },

  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    textTransform: 'uppercase' as const,
    margin: '0 0',
  },
  spinner: {
    fontSize: '24px',
    color: '#4CAF50',
    animation: 'spin 1s linear infinite',
  },
  '@keyframes spin': {
    '0%': { transform: 'rotate(0deg)' },
    '100%': { transform: 'rotate(360deg)' },
  },

  skeletonContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'center',
    alignItems: 'center',
    gap: '20px',
    padding: '20px',
    textAlign: 'center' as const,
  },
  skeletonTitle: {
    width: '200px',
    height: '30px',
    backgroundColor: '#e0e0e0',
    borderRadius: '4px',
    animation: 'pulse 1.5s infinite',
  },
  skeletonLine: {
    width: '150px',
    height: '20px',
    backgroundColor: '#e0e0e0',
    borderRadius: '4px',
    animation: 'pulse 1.5s infinite',
  },
  skeletonRow: {
    display: 'flex',
    justifyContent: 'center',
    gap: '10px',
  },
  skeletonCircle: {
    width: '50px',
    height: '50px',
    backgroundColor: '#e0e0e0',
    borderRadius: '50%',
    animation: 'pulse 1.5s infinite',
  },
  '@keyframes pulse': {
    '0%': { opacity: 1 },
    '50%': { opacity: 0.5 },
    '100%': { opacity: 1 },
  },

  // Navbar e Menu
  navbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#282c34',
    padding: '20px 0px',
    color: '#ffffff',
    fontFamily: "'Poppins', sans-serif",
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    top: 0,
    left: 0,
    width: '100%',
    position: 'absolute' as const,
    height: '50px',
  },
  divLogo: {
    display: 'flex',
  },
  buttonLogo: {
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: 0,
  },
  logo: {
    width: '150px',
  },
  links: {
    display: 'flex',
    gap: '20px',
    padding: '0 50px',
  },
  linkButton: {
    textDecoration: 'none',
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#ffffff',
    backgroundColor: '#4CAF50',
    padding: '10px 20px',
    borderRadius: '8px',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.3)',
    transition: 'background-color 0.3s, transform 0.2s',
    cursor: 'pointer',
    display: 'inline-block',
  },

  // Botões
  welcomeBtn: {
    backgroundColor: '#4CAF50',
    color: '#ffffff',
    padding: '10px 20px',
    borderRadius: '8px',
    border: 'none',
    fontSize: '16px',
    cursor: 'pointer',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.3)',
    transition: 'background-color 0.3s, transform 0.2s',
    ':hover': {
      backgroundColor: '#45a049',
      transform: 'scale(1.05)',
    },
  },
  clearBtn: {
    backgroundColor: '#800020',
    color: '#fff',
    padding: '10px 20px',
    borderRadius: '8px',
    border: 'none',
    fontSize: '16px',
    cursor: 'pointer',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.3)',
    transition: 'background-color 0.3s, transform 0.2s',
    ':hover': {
      backgroundColor: '#CC0000',
      transform: 'scale(1.05)',
    },
  },

  // Componentes
  attemptContainer: {
    display: 'flex',
    gap: '10px',
    padding: '10px',
    marginBottom: '5px',
    border: '1px solid #209869',
    borderRadius: '12px',
  },
  suggestion: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '10px',
    paddingBottom: '10px',
  },
  numero: {
    backgroundColor: '#209869',
    color: '#ffffff',
    padding: '2px',
    borderRadius: '50%',
    width: '50px',
    height: '50px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    fontWeight: 'bold',
    margin: '5px',
    cursor: 'pointer',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.3)',
    transition: 'transform 0.2s, box-shadow 0.2s',
    ':hover': {
      transform: 'scale(1.1)',
      boxShadow: '0 6px 15px rgba(0, 0, 0, 0.5)',
    },
  },

  container: {
    paddingTop: '70px',
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'flex-start',
    alignItems: 'center',
    height: '100vh', // Centraliza verticalmente
    width: '100%', // Garante que ocupe toda a largura
    gap: '20px', // Espaçamento entre os elementos
  },
  buttonContainer: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    justifyContent: 'center',
    gap: '10px',
    width: '100%',
    maxWidth: '800px',
  },
  otherLinkBtn: {
    textDecoration: 'none',
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#ffffff',
    backgroundColor: '#4CAF50',
    padding: '10px 20px',
    borderRadius: '8px',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.3)',
    transition: 'background-color 0.3s, transform 0.2s',
    cursor: 'pointer',
    display: 'inline-block',
    ':hover': {
      backgroundColor: '#45a049',
      transform: 'scale(1.05)',
    },
  },
  cardContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    maxWidth: '700px', // Limita a largura máxima do card
  },
  message: {
    fontSize: '18px',
    color: '#fff',
  },
};
