export const styles = {
  mainContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100vw',
    height: '100vh',
    backgroundColor: '#1e1e2f',
    fontFamily: "'Poppins', sans-serif",
  },
  appContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    backgroundColor: 'rgba(36, 36, 36, 0.9)',
    padding: '30px',
    borderRadius: '15px',
    color: '#f5f5f5',
    fontFamily: "'Poppins', sans-serif",
    border: '1px solid rgba(255, 255, 255, 0.2)',
    maxWidth: '1000px',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.37)',
    backdropFilter: 'blur(10px)',
  },
  exercicioContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    backgroundColor: 'rgba(85, 85, 85, 0.8)',
    padding: '20px',
    borderRadius: '15px',
    color: '#ffffff',
    marginBottom: '20px',
    fontFamily: "'Poppins', sans-serif",
    width: '570px',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.25)',
    backdropFilter: 'blur(8px)',
  },
  displayContainer: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '10px',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    borderRadius: '10px',
    minHeight: '60px',
  },
  noInputText: {
    fontWeight: 'bold',
    fontSize: '16px',
  },
  titulo: (color: string) => ({
    fontSize: '28px',
    color,
    alignSelf: 'flex-start',
    fontWeight: '600',
    textShadow: '0 2px 4px rgba(0, 0, 0, 0.5)',
  }),
  inputQuantidade: {
    margin: '10px 0',
    padding: '10px',
    borderRadius: '8px',
    border: '1px solid rgba(255, 255, 255, 0.8)',
    fontSize: '16px',
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    color: '#000',
    fontFamily: "'Poppins', sans-serif",
    outline: 'none',
    boxShadow: 'inset 0 2px 4px rgba(0, 0, 0, 0.2)',
  },
  listaNumeros: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    justifyContent: 'center',
    marginTop: '20px',
    gap: '10px',
  },
  numero: (backgroundColor: string) => ({
    backgroundColor,
    color: '#ffffff',
    padding: '15px',
    borderRadius: '50%',
    width: '50px',
    height: '50px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    fontWeight: 'bold',
    margin: '5px',
    cursor: 'pointer',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.3)',
    transition: 'transform 0.2s, box-shadow 0.2s',
    ':hover': {
      transform: 'scale(1.1)',
      boxShadow: '0 6px 15px rgba(0, 0, 0, 0.5)',
    },
  }),
};