export const styles = {
  mainContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100vw',
    height: '100vh',
    backgroundColor: '#333',
  },
  appContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    backgroundColor: '#242424',
    padding: '20px',
    borderRadius: '10px',
    color: 'white',
    fontFamily: 'Arial, sans-serif',
    border: '2px solid #000',
    maxWidth: '600px',
  },
  exercicioContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    backgroundColor: '#555555',
    padding: '20px',
    borderRadius: '10px',
    color: 'white',
    marginBottom: '20px',
    fontFamily: 'Arial, sans-serif',
    minWidth: '400px',
  },
  titulo: (color: string) => ({
    fontSize: '24px',
    color,
    alignSelf: 'flex-start',
  }),
  inputQuantidade: {
    margin: '10px 0',
    padding: '5px',
    borderRadius: '5px',
    border: 'none',
    fontSize: '14px',
    width: '100%',
    backgroundColor: 'white',
    color: 'black',
  },
  listaNumeros: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    justifyContent: 'center',
    marginTop: '20px',
  },
  numero: (backgroundColor: string) => ({
    backgroundColor,
    color: 'white',
    padding: '10px',
    borderRadius: '50%',
    width: '40px',
    height: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '16px',
    margin: '5px',
    cursor: 'pointer',
  }),
};
